site_name: Портфолио
site_url: https://healbane.github.io
site_author: Орлов Михаил

theme:
  name: material
  language: ru

  palette:
    # Темная тема по умолчанию
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

    # Светлая тема
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - def_list

plugins:
  - search:
      lang: ru

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - labs/index.md
      - Лабораторная работа 1: labs/lab1.md
      - Лабораторная работа 2: labs/lab2.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/healbane
    - icon: fontawesome/brands/telegram
      link: https://t.me/OneEyedVisceral
    - icon: fontawesome/solid/envelope
      link: mailto:healbane@gmail.com